### ISSUE TITLE
v3.35.0 - ModuleNotFoundError: No module named 'certifi'

### ISSUE THREAD

**Issue by codeaprendiz** [oracle/oci-cli#723] opened 2023-10-25 16:36 UTC
# v3.35.0 - ModuleNotFoundError: No module named 'certifi' 

### OS Info

M1 Mac : 14.0

### Steps

- Install the `oci-cli`

> Tried uninstall and installing 3 times

```bash
# To uninstall : brew uninstall oci-cli
# To reinstall : brew reinstall oci-cli
brew install oci-cli
```
- Run oci command

```bash
oci -h
```
 Output

```bash
..
..
 File "/opt/homebrew/Cellar/oci-cli/3.35.0/libexec/lib/python3.12/site-packages/oci/_vendor/requests/certs.py", line 20, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'
```

I see that the package `v3.35.0` was released 20 hours back.

So as a workaround had to manually install [v3.34.0](https://github.com/oracle/oci-cli/releases/tag/v3.34.0) by following [docs.oracle.com » Manual and Offline Installations](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/climanualinst.htm#climanualinst_intro) which is working for the time being.

**Comment by treethought** [comment] 2023-10-26 19:14
have the same issue. after installing certifi, i then get `ModuleNotFoundError: No module named 'six'` even after uninstalling/reinstalling oci

**Comment by codeaprendiz** [comment] 2023-10-27 06:26
Yes, I also went the process of installing corresponding packages for `certifi` and then `six` errors. It might be become tedious and unpredictable by trying to make it work by installing packages manually. 
So I decided to downgrade the version of `oci-cli` to `v3.34.0`. It seems to be working fine for all of my requirements so far.

**Comment by MichaelPak** [comment] 2023-10-31 14:39
Same issue but with the `click` module:
```
$ brew upgrade oci-cli
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################### 100.0%
Warning: oci-cli 3.35.0 already installed

$ oci vault secret list -c ocid1.compartment.oc1..somecompartment
Traceback (most recent call last):
  File "/opt/homebrew/bin/oci", line 5, in <module>
    from oci_cli.cli import cli
  File "/opt/homebrew/Cellar/oci-cli/3.35.0/libexec/lib/python3.12/site-packages/oci_cli/__init__.py", line 24, in <module>
    from oci_cli.cli_root import cli  # noqa: F401,E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/oci-cli/3.35.0/libexec/lib/python3.12/site-packages/oci_cli/cli_root.py", line 11, in <module>
    import click    # noqa: E402
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'click'
```

**Comment by Djelibeybi** [comment] 2023-11-01 00:52
This is a Homebrew error caused by the unexpected dependency bump to Python 3.12 for all Python-based Homebrew recipes. The current fix is to run:

```bash
brew reinstall cffi python-certifi python-click python-cryptography python-pytz pyyaml six
brew install oci-cli
```

You may need to run `brew reinstall ...` for a dependency more than once. Essentially run the reinstall command on any dependency you're getting a "No module found" for.

**Comment by karthik-k-kamath** [comment] 2023-11-02 06:28
Closing this as it is a know issue with above solution.
Feel free to reopen, incase solution does not work.

**Closed by karthik-k-kamath** 2023-11-02 06:28 UTC
