### ISSUE TITLE
Default profile is not getting loaded even if I have a default profile

### ISSUE THREAD

**Issue by KirankBadiger** [oracle/oci-cli#440] opened 2021-08-13 07:07 UTC
[DEFAULT]
user=user ocid who has admin privilege to OCI console
fingerprint=fingerprint
key_file=path/to/pemkey/file
tenancy=tenancy-ocid
region=ap-mumbai-1

**Comment by vish1** [comment] 2021-08-18 23:42
@KirankBadiger Can you provide the error that you are getting? In some cases, manually created files may have some encoding related issues which might lead to CLI not reading the file. Can you use `oci setup config` command to recreate the config file and try?

**Comment by fpiecka** [comment] 2021-08-25 14:33
I think this could be the same problem I am facing.

The problem is an incompatibility with a newer Click Python package. I have Click 8.0.1 and my default section is called "\<DEFAULT\>".

It seems the culprit is at: https://github.com/oracle/oci-cli/blob/37230ac988874eeaff3f8ca4d7a3b9b69ab0d61f/src/oci_cli/cli_root.py#L348

`profile` is string and `Sentinel(DEFAULT_PROFILE)` is an object.

On a system with click 6.7, `profile` is an object too and the expression works as expected.

**Comment by kernleee** [comment] 2021-11-18 18:52
I will be closing this issue since this is specific to a click version we do not currently use. If this issue reappears, I would recommend installing the cli in a venv, so no dependency conflicts arise.

**Closed by kernleee** 2021-11-18 18:52 UTC
Labels: SDK
